# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

tasks:
  build-jar:
    desc: Build a fat JAR ready to run
    dir: backend
    cmd: ./mvnw clean package -DskipTests
  
  build-native:
    desc: Build a binary-native image
    dir: backend
    cmd: time ./mvnw -Pnative package

  dev-up:
    desc: Run the app in dev mode
    cmd: docker compose -f compose.dev.yaml up -d

  dev-down:
    desc: Stops the database and backend
    cmd: docker compose -f compose.dev.yaml down -v --remove-orphans

  prod-like-up:
    desc: Starts database and two instances using OS-native binary backend
    cmd: docker compose up -d

  prod-like-down:
    desc: Stops database and the backend instances
    cmd: docker compose down -v --remove-orphans

  run-native-tracing:
    desc: Buidl and run with native agent to trace reflections
    dir: backend
    deps: [db-up]
    cmd: |
      ./mvnw clean package -DskipTests && \
        java -agentlib:native-image-agent=config-output-dir=src/main/resources/META-INF/native-image \
        -jar target/rinha2026-1.0-SNAPSHOT.jar

  run-native:
    desc: Run the native binary
    deps: [db-up]
    cmd: export ORDER_DB_MIGRATIONS_PATH="backend/db/migration" && ./backend/target/app-native

  test:
    desc: Run tests
    dir: backend
    cmd: ./mvnw test

  db-up:
    desc: Starts the database using Docker
    cmd: docker compose -f compose.dev.yaml up rinha-db -d

  db-down:
    desc: Stops the database using Docker
    cmd: docker compose -f compose.dev.yaml down rinha-db -v --remove-orphans

