# Override any value with env vars like ORDER_SERVER_PORT
# Server
order.server.port=9999

# Database
order.db.url=jdbc:postgresql://localhost:5432/rinha
order.db.user=rinha
order.db.password=rinha
order.db.max.pool.size=10
order.db.pool.name=rinha-pool

# Migrations
rinha. javalin/db/migration

