# Override any value with env vars like RINHA_SERVER_PORT
# Server
rinha.server.port=8080
rinha.server.instance=_one

# Database
rinha.db.url=jdbc:postgresql://localhost:5432/rinha
rinha.db.user=rinha
rinha.db.password=rinha
rinha.db.max.pool.size=10
rinha.db.pool.name=rinha-pool

# Migrations
rinha. javalin/db/migration

